const actionTypes = {
  ADD_POINT: "ADD_POINT",
  CHANGE_POINT_INFO: "CHANGE_POINT_INFO",
  CHANGE_POINT_ORDER: "CHANGE_POINT_ORDER",
  DELETE_POINT: "DELETE_POINT",
  SET_MAP_API: "SET_MAP_API",
  CHANGE_API: "CHANGE_API",
  SET_MAP: "SET_MAP"
};

export default actionTypes;
